[colors]
ansi = [
  '#060914',
  '#4E0E0E',
  '#1C4642',
  '#543407',
  '#0D2C4E',
  '#4C1036',
  '#104351',
  '#878996',
]
brights = [
  '#1D202B',
  '#913B3B',
  '#697F4D',
  '#A06A2C',
  '#42608A',
  '#8D3F5A',
  '#478584',
  '#BDBFCB',
]


background = '#BDBFCB'
foreground = '#060914'

cursor_bg = '#060914'
cursor_fg = '#BDBFCB'

compose_cursor = '#1C4642'
cursor_border = '#060914'

scrollbar_thumb = '#343742'

selection_bg = '#343742'
selection_fg = '#BDBFCB'

split = '#343742'
visual_bell = '#343742'


[colors.tab_bar]
background = '#878996'
inactive_tab_edge = 'BDBFCB'

[colors.tab_bar.active_tab]
bg_color = '#BDBFCB'
fg_color = '#060914'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#878996'
fg_color = '#1D202B'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#A7A9B5'
fg_color = '#121520'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#878996'
fg_color = '#141712'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#A9D07C'
fg_color = '#141712'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
name = 'Yorumi Mist'
