[colors]
ansi = [
  '#0E121F',
  '#913B3B',
  '#697F4D',
  '#9D672F',
  '#42608A',
  '#8D3F5A',
  '#478584',
  '#878996',
]
brights = [
  '#343742',
  '#C65E53',
  '#8CB167',
  '#C39D55',
  '#597BC0',
  '#BB5D7D',
  '#67BBB9',
  '#A7A9B5',
]

background = '#0E0D17'
foreground = '#A7A9B5'


cursor_bg = '#C6DFEC'
cursor_fg = '#060914'

compose_cursor = '#D7E1B7'
cursor_border = '#BDBFCB'

scrollbar_thumb = '#343742'

selection_bg = '#343742'
selection_fg = '#BDBFCB'

split = '#343742'
visual_bell = '#343742'


[colors.tab_bar]
background = '#0E0D17'
inactive_tab_edge = '#AD8FD6'

[colors.tab_bar.active_tab]
bg_color = '#0E0D17'
fg_color = '#BDBFCB'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#121520'
fg_color = '#A7A9B5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#0E0D17'
fg_color = '#BDBFCB'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#121520'
fg_color = '#A9D07C'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#A9D07C'
fg_color = '#141712'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
name = 'Yorumi Kraken'
