[colors]
ansi = [
  '#0E121F',
  '#913B3B',
  '#697F4D',
  '#9D672F',
  '#42608A',
  '#614686',
  '#478584',
  '#A7A9B5',
]
brights = [
  '#343742',
  '#F47571',
  '#A9D07C',
  '#E1C084',
  '#798DDC',
  '#AD8FD6',
  '#85E0CB',
  '#C0BCE6',
]

background = '#0E0D17'
foreground = '#C0BCE6'


cursor_bg = '#C0BCE6'
cursor_fg = '#0E0D17'

compose_cursor = '#2A1844'
cursor_border = '#AD8FD6'

scrollbar_thumb = '#343742'

selection_bg = '#121520'
selection_fg = '#C0BCE6'

split = '#343742'
visual_bell = '#343742'


[colors.tab_bar]
background = '#0E0D17'
inactive_tab_edge = '#AD8FD6'

[colors.tab_bar.active_tab]
bg_color = '#0E0D17'
fg_color = '#C0BCE6'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#121520'
fg_color = '#A7A9B5'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#0E0D17'
fg_color = '#BDBFCB'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#121520'
fg_color = '#A9D07C'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#A9D07C'
fg_color = '#141712'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
name = 'Yorumi Kraken'
