[colors]
ansi = [
  '#0F1015',
  '#913B3B',
  '#697F4D',
  '#9D672F',
  '#42608A',
  '#8D3F5A',
  '#478584',
  '#878996',
]
brights = [
  '#343742',
  '#C65E53',
  '#8CB167',
  '#C39D55',
  '#597BC0',
  '#BB5D7D',
  '#67BBB9',
  '#BDBFCB',
]


background = '#0F1015'
foreground = '#BDBFCB'

cursor_bg = '#878996'
cursor_fg = '#060914'

compose_cursor = '#C6DFEC'
cursor_border = '#BDBFCB'

scrollbar_thumb = '#343742'

selection_bg = '#343742'
selection_fg = '#BDBFCB'

split = '#1D202B'
visual_bell = '#1D202B'


[colors.tab_bar]
background = '#15171D'
inactive_tab_edge = '#878996'

[colors.tab_bar.active_tab]
bg_color = '#0F1015'
fg_color = '#BDBFCB'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#15171D'
fg_color = '#878996'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#121520'
fg_color = '#BDBFCB'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#1D202B'
fg_color = '#A9D07C'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#141712'
fg_color = '#85E0CB'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
name = 'Yorumi Shade'
