[colors]
ansi = [
    "#060914",  # Yoru0 (Ideal for background)
    "#913B3B",  # UmiRed
    "#667C4B",  # UmiGreen
    "#9D672F",  # UmiYellow
    "#42778A",  # UmiBlue
    "#8D3F5A",  # UmiMagenta
    "#49837E",  # UmiCyan
    "#C6DFEC"   # Tsuki4 (White for clarity)
]

background = "#121520"  # Yoru2 for background
foreground = "#BDBFCB"  # Tsuki3 for foreground (light, good contrast)

brights = [
    "#1D202B",  # Yoru3 (For fold columns and auxiliary UI components)
    "#F05C60",  # SangoRed
    "#80AA6E",  # SangoGreen
    "#BA9A5E",  # SangoYellow
    "#597BC0",  # SangoBlue
    "#B4647F",  # SangoMagenta
    "#7AA8A7",  # SangoCyan
    "#F3AB59"   # KairoOrange
]
cursor_bg =  "#C6DFEC" # Tsuki4 for cursor background
cursor_border = "#C6DFEC"  # Tsuki4 for cursor border
cursor_fg = "#BDBFCB"  # Tsuki3 for cursor foreground
selection_bg = "#343742"  # KuroiGray for selection background
selection_fg = "#BDBFCB"  # Tsuki3 for selection foreground

[colors.indexed]
16 = "#F3AB59"  # KairoOrange
17 = "#85C7B8"  # KairoCyan
18 = "#597BC0"  # SangoBlue
19 = "#80AA6E"  # SangoGreen
20 = "#F05C60"  # SangoRed
21 = "#9D7BBF"  # KairoViolet

[metadata]
name = "yorumi_cloud"

